### PR TITLE
Add typescript definition file

### PR DESCRIPTION
**Pull request by koddsson**
@cheshire137 Can you test this in your project? I think this is correct but I'd love a second pair of 👀

Ref: https://github.com/github/web-systems/issues/223

### CODE REVIEW

**Comment by cheshire137** [comment]
What do you think is the best way to verify this? Save the files from this branch into the node_modules time-elements directory and see if the warnings go away when I import the package?

**Comment by koddsson** [comment]
You can install the code from this PR directly like so:

```sh
npm install --save github/time-elements#add-typescript-definition-file
```

And after you are done testing you can go back to using the code from npm with:

```sh
npm remove @github/time-elements
npm install --save @github/time-elements
```

**Comment by koddsson** [comment]
@cheshire137 Did you have a chance to check this out? If I can help in any way, just let me know ✨

**Comment by koddsson** [comment]
Merging this! 👾

**Pull request merged**
