### PR TITLE
RelativeTime: Support custom format

### PR DESCRIPTION
**Pull request by nomego**
Allow user to supply a strftime() format through the format
attribute, to be used when outside the relative time scope.

### CODE REVIEW

**Comment by tobyzerner** [comment]
Any chance of this getting merged?

**Comment by bankoViktor** [comment]
Can we expect action in the near future on this issue?

**Review by keithamus — APPROVED** [review]
This LGTM :+1: 

Some tests would be nice to confirm this behavior, but otherwise I think this is a worthwhile changes.

/cc @github/ui-frameworks for a second review

**Review by koddsson — APPROVED** [review]
Yeah, tests would be great. We've missed this PR for quite some time so it needs some rebasing but otherwise this LGTM

**Comment by keithamus** [comment]
This was merged in via #177, thanks for working on this @nomego! I'll get a release out with a few other things this week!

**Pull request closed without merging**
